### ISSUE TITLE
Add debug related print messages to instruction set simulator

### ISSUE THREAD

**Issue by raulbehl** [SimpleCPU/SimpleCPU#1]
There aren't any debug related print messages added to the ISS. Adding print messages related to instruction type, address, etc would be really helpful. 
Also, on stand-alone test runs on model - there isn't any output. A proper log should be created for those runs.

**Comment by dhruvbehl** [comment]
Added few R, I and J type instructions' print statements, also added print functions for I and J type.
Need to revamp the logic of the print functions to support Jump and MULT type instructions to accommodate HI, LO and SHIFT values in the display.

**Comment by dhruvbehl** [comment]
Added debug messages to all R, I and J type instructions.

**Comment by raulbehl** [comment]
Fixed in commit #[8105012 ](https://github.com/SimpleCPU/SimpleCPU/commit/8105012b55408f33f6c9ed00c47b4a7d6446d113)
