### ISSUE TITLE
Enable Branch instruction in hex-gen

### ISSUE THREAD

**Issue by guptasanchi** [SimpleCPU/SimpleCPU#10]
It was recently found out that the hex-gen tool was not generating any branch instructions. On reviewing the code it was found that the branch instructions were commented out. The RTL now supports simple branch instructions and hence should be enabled in the hex-gen tool.

**Comment by raulbehl** [comment]
Fix in [aa7f27d](https://github.com/SimpleCPU/SimpleCPU/commit/aa7f27d919cb98ab886394620afc69ecb4aaae2d)
