### ISSUE TITLE
Incomplete simulation flow for mips-pipeline implementation

### ISSUE THREAD

**Issue by guptasanchi** [SimpleCPU/SimpleCPU#13]
The flow for MIPS 5-stage pipeline isn't complete. The RTL still needs to add the hazard and forwarding logic. The testbench needs to be updated for the pipelined signals. The DPI calls would also need to be factored for the correct instruction opcode.

**Comment by raulbehl** [comment]
The flow is up now. I have updated both RTL and TB components.
