### ISSUE TITLE
HEX-GEN tool generating instructions at same PC offset

### ISSUE THREAD

**Issue by raulbehl** [SimpleCPU/SimpleCPU#15]
There seems to be some issue with the way hex_gen is generating Jump/branch instructions. The jump and branch target seems to update PC to a free location but sometimes depending on the jump/branch target the subsequent sequential instructions are generated on an already taken PC. The following PC trace shows the different values of PC for 50 I-type instructions - 
0
4
8
c
10 Branch to 2b4
2b4
2b8
2bc
2c0
2c4
2c8
2cc
2d0
2d4
2d8
2dc
534
3a0
3a4
3a8
3ac
414
418
41c
41c
420
424
dfc
8b0
8b4
8b8
8bc
8c0
8c4
d30
d34
730
2b4
d54
d58
1cc
1d0
1d4
1d8 Branch to 2a8
2a8 
2ac
2b0
2b4 (already used PC being accessed again)
2b8
2bc
2c0
2c4

**Comment by guptasanchi** [comment]
This looks like a major issue with respect to branch/jump instruction generation. 
After having discussed this with @dhruvbehl we have come up with a fix. But this fix might require a bit of code re-factoring. So, giving a heads up on that.

**Comment by guptasanchi** [comment]
Fix checked in d5eb686
Closing.
