### ISSUE TITLE
RTL doesn't link the register on branch and link instructions

### ISSUE THREAD

**Issue by guptasanchi** [SimpleCPU/SimpleCPU#16]
On testing the newly added branch instruction variants, it was found that the RTL doesn't update the R31 register on branch & link instructions. This leads to tests failing with mismatches. 
As per the MIPS ISA, the register should be updated with CURRENT PC + 4. RTL should be updated to implement this feature.

**Comment by raulbehl** [comment]
Yes, this sounds like a bug to me. I will add this functionality today. Though for aggressive testing we need #15 to be resolved.

**Comment by raulbehl** [comment]
This looks like an involved issue. Might require few more updates to TB/RTL.

**Comment by raulbehl** [comment]
Fix in master.
