### ISSUE TITLE
Add tests targeting load/store instructions, branch instructions, ALU ops

### ISSUE THREAD

**Issue by raulbehl** [SimpleCPU/SimpleCPU#18]
The current test directory inside hex-gen tool doesn't give any information on the major type of instructions the test contains. It would be good to organise the directory properly with tests focusing on load/store unit, branch/jump and different ALU ops.

**Comment by guptasanchi** [comment]
All the relevant test cases have been checked in to their respective directories. Please check 
hex_gen/tests/  directory for further information.
