### ISSUE TITLE
Add a regression manager script

### ISSUE THREAD

**Issue by raulbehl** [SimpleCPU/SimpleCPU#19]
There are a lot of test getting generated and added to the repo. All the tests for the implementation are checked-in at mips/hex_gen/tests/

There should be a script to run a regression of those tests and report any fails seen. This would help in flushing out bugs quickly.

**Comment by dhruvbehl** [comment]
Initial support for regression manger is added and will be revamped according to the future enhancements
Closing with commit# fc07f2e
