### ISSUE TITLE
Regression manager script doesn't report any outputs/stats about the tests

### ISSUE THREAD

**Issue by raulbehl** [SimpleCPU/SimpleCPU#24]
I see the following output when I run the regressionManager script - 
```
**********Running tests from: ../hex_gen/tests/test_alu_ops/hex/**********
**********Running tests from: ../hex_gen/tests/test_alu_ops/hex/**********
**********Running tests from: ../hex_gen/tests/test_i_type_instr/hex/**********
**********Running tests from: ../hex_gen/tests/test_i_type_instr/hex/**********
**********Running tests from: ../hex_gen/tests/test_j_type_instr/hex/**********
**********Running tests from: ../hex_gen/tests/test_j_type_instr/hex/**********
**********Running tests from: ../hex_gen/tests/test_all_instr/hex/**********
**********Running tests from: ../hex_gen/tests/test_all_instr/hex/**********
```
The above output doesn't convey whether the test passed or failed? Even the contents of results.txt just contain the output from the final test ( ../hex_gen/tests/test_all_instr/hex/). All other outputs are overwritten. It would be good to have the script to output prints to shell. Also, the results.txt file should contain output for all the failed tests. This would help in debugging the fail quickly.

**Comment by dhruvbehl** [comment]
Closing the issue after recent commits to regression manager script. New logic for regression test log parser added.
