### ISSUE TITLE
Parameterize the test name hex in both model and testbench

### ISSUE THREAD

**Issue by guptasanchi** [SimpleCPU/SimpleCPU#25]
The model and TB are both hardcoded to read the instructions from a file named as "instr_hex" and the corresponding PC values from "pc_values_hex". Both the model and TB should allow the user to read the test name from the command line. I was thinking we can follow the following convention - 
<test_name>.hex
<test_name>_pc.hex

On the command line the user can just provide the test name and the rest should be taken care of.

**Comment by raulbehl** [comment]
I will take care of updating the TB. 
@dhruvbehl can you check the same for the ISS?

**Comment by raulbehl** [comment]
I have added the support in the TB and the run.pl script as well. 
Fix in 0b6e052

**Comment by guptasanchi** [comment]
Added the required support in the model as well. 
Closing.

**Comment by guptasanchi** [comment]
@raulbehl  It should be good to retain all the labels even after the bug is fixed.
