### ISSUE TITLE
Check PC updates to be within the TEXT area

### ISSUE THREAD

**Issue by raulbehl** [SimpleCPU/SimpleCPU#8]
As per the comment in #7 - 
There seems to be some issue with the way hex_gen is generating Jump instructions. What I noticed was that the hex_gen takes care of the jump address to be within the TEXT area but the subsequent instructions do not follow this. In one of the tests I saw that the jump instruction takes the PC to 0xFFC (which is within the TEXT area - 0x0000-0x1000) but then the subsequent instruction were generated at PC values of 0x1000, 0x1004, etc which is incorrect.
There should be a check placed whenever the PC is updated. I will open a new bug for this.

**Comment by guptasanchi** [comment]
The above case depends on the target value generated for the jump instructions - which is completely a 26-bit random value. But yes, there are no checks placed for checking out-of-bounds PC updates. This do qualifies as a bug in both hex_gen and the model - though fix would only be required in the C-model. The instruction at the last valid PC should branch to the top most free PC space. Therefore hex_gen should automatically insert the branch whenever PC value is equal to 0xFFC. There would be some logic required to get the top most free PC space.

**Comment by guptasanchi** [comment]
I have updated the model and the hex-gen to avoid creating such scenarios. In the patch attached below, I have restricted the jump address to be from 0x0-0xF00 and also updated hex-gen to avoid creating already used PC as a branch/jump target. 

@dhruvbehl Can you please review it once before I check it in?

Thank you!
[pc.txt](https://github.com/SimpleCPU/SimpleCPU/files/757042/pc.txt)

**Comment by raulbehl** [comment]
@guptasanchi  I have tested the patch on the latest checkout and seems to work well with the RTL as well. Thank you for the quick fix. Please close the bug once you check-in the changes.

**Comment by guptasanchi** [comment]
Fix in [0c361d0](https://github.com/SimpleCPU/SimpleCPU/commit/0c361d0da4304b921e65bfb69f201d4982ac0a78)
